apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.myscret.myreposecretname }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appname }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerConfig | toJson | b64enc | quote }}