apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.myservice.servicename }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.appname }}
  ports:
    - protocol: {{ .Values.myservice.myprotocol }}
      port: {{ .Values.myservice.port }}
      targetPort: {{ .Values.myimage.containerandtargetPort }}
  type: {{ .Values.myservice.type }}